apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base

resources:
  - "https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml"
  - "rabbitmq-ingress.yml"

patchesStrategicMerge:
  - "rabbitmq-cluster-default.yml"
