apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: default-cluster
spec:
  image: rabbitmq:3.10.7
  replicas: 3
  rabbitmq:
    additionalConfig: |
      cluster_partition_handling = pause_minority
      vm_memory_high_watermark_paging_ratio = 0.99
      disk_free_limit.relative = 1.0
      collect_statistics_interval = 10000
