apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# bases:
#   - ../argocd

resources:
  # - "argocd_namespace.yml"
  # - "https://github.com/cert-manager/cert-manager/releases/download/v1.8.1/cert-manager.yaml"
  - "https://github.com/rabbitmq/cluster-operator/releases/latest/download/cluster-operator.yml"
  - "rabbitmq-cluster-default.yml"
  - "pod-disruption-budget.yml"
